# Generated by Django 3.1.3 on 2020-11-14 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_picture', models.ImageField(upload_to='products/images')),
                ('prod_price', models.FloatField(default=0, max_length=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('in_terms_of', models.CharField(choices=[('Kg', 'Kg'), ('L', 'L'), ('Pack', 'Pack'), ('Piece', 'Piece'), ('Quarter', 'Quarter'), ('Square cm', 'Square cm'), ('Square m', 'Square m'), ('Unit', 'Unit'), ('cm', 'cm'), ('db', 'db'), ('dozen', 'dozen'), ('ft', 'ft'), ('gallon', 'gallon'), ('gm', 'gm'), ('inch', 'inch'), ('m', 'm'), ('mg', 'mg'), ('ml', 'ml'), ('mm', 'mm'), ('pound', 'pound'), ('square ft', 'square ft'), ('tone', 'tone'), ('watt', 'watt')], default='Kg', max_length=10)),
                ('country_Of_Origin', models.CharField(choices=[('Australia', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Germany', 'Germany'), ('Hong Kong', 'Hong Kong'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Israel', 'Israel'), ('Japan', 'Japan'), ('Kuwait', 'Kuwait'), ('Malaysia', 'Malaysia'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('Nigeria', 'Nigeria'), ('Qatar', 'Qatar'), ('Russia', 'Russia'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('Singapore', 'Singapore'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('UAE', 'UAE'), ('UK', 'UK'), ('US', 'US'), ('Venezuela', 'Venezuela')], default='India', max_length=25)),
                ('prod_description', models.TextField()),
                ('prod_offer', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
